[project]
name = "mail"
authors = [
    { name = "Frappe Technologies Pvt. Ltd.", email = "developers@frappe.io"}
]
description = "Frappe Mail"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
    "wrapt~=1.17.3",
    "bcrypt~=4.2.1",
    "py3dns~=4.0.2",
    "pexpect~=4.9.0",
    "paramiko~=4.0.0",
    "dnspython~=2.4.2",
    "dns-lexicon~=3.20.1",
    "markdown-it-py~=4.0.0",
    "ansible-runner~=2.4.1",
    "validate-email-address~=1.0.0",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
]
ignore = [
    "B017", # assertRaises(Exception) - should be more specific
    "B018", # useless expression, not assigned to anything
    "B023", # function doesn't bind loop variable - will have last iteration's value
    "B904", # raise inside except without from
    "E101", # indentation contains mixed spaces and tabs
    "E402", # module level import not at top of file
    "E501", # line too long
    "E741", # ambiguous variable name
    "F401", # "unused" imports
    "F403", # can't detect undefined names from * import
    "F405", # can't detect undefined names from * import
    "F722", # syntax error in forward type annotation
    "W191", # indentation contains tabs
]
typing-modules = ["frappe.types.DF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true

[deploy.dependencies.apt]
packages = [
    "ansible",
]